name: adic_poc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  http: ^1.1.0
  flutter_appauth: ^6.0.2
  shared_preferences: ^2.5.3
  # Isar database dependencies
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Isar generator
  isar_generator: ^3.1.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
